### PR TITLE
489 observables

### PR DESCRIPTION
**Pull request by bmheadley**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.
Solves issue #489 adding additional configuration for observables
<br/><br/>

2. What **changes to custom.yaml** are required?
Greymatter.yaml has 1 added value (useKafka) for the ability to configure the observable filter
<br/><br/>

3. Have you documented any additional setup steps or configurations options?
Additonal configuration is through values.yaml, with observablesEnabled and useKafka booleans. 
<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Tested in k3d
<br/><br/>

### CODE REVIEW

**Comment by moosecanswim** [comment]
@bmheadley this does make a change to the custom values file (we should change the pr script to say graymatter.yaml as its confusing rn)!
```     
observablesEnabled: true
useKafka: true
```

**Comment by moosecanswim** [comment]
Using `controlApi.observablesENnabled:true` and `controlApi.useKafka: true`

**Comment by moosecanswim** [comment]
@bmheadley 
Using `controlApi.observablesENnabled:true` and `controlApi.useKafka: false`
i get a working dashboard but `gm get proxy proxy-gm-control-api` fails.  looking at configmap service-gm-control-api-mesh-config shows that there is that pesky spacing issue.

```
Kyles-MacBook-Pro-3:helm-charts kyleg$ kc get configmap service-gm-control-api-mesh-config -o yaml
apiVersion: v1
data:
  cluster.json: |-
    {
      "cluster_key": "cluster-gm-control-api",
      "zone_key": "zone-default-zone",
      "name": "service",
      "instances": [
        {
            "host": "0.0.0.0",
            "port": 5555
        }
      ],
      "require_tls": true,
      "ssl_config": {
          "protocols": [
            "SSLv3",
            "SSLv2",
            "TLSv1",
            "TLSv1.1",
            "TLSv1.2"
          ],
        "require_client_certs": true,
        "trust_file": "/etc/proxy/tls/sidecar/ca.crt",
        "cert_key_pairs": [
          {
            "certificate_path": "/etc/proxy/tls/sidecar/server.crt",
            "key_path": "/etc/proxy/tls/sidecar/server.key"
          }
        ]
      },
      "circuit_breakers": null,
      "outlier_detection": null,
      "health_checks": []
    }
  domain.json: |-
    {
      "domain_key": "domain-gm-control-api",
      "zone_key": "zone-default-zone",
      "name": "*",
      "port": 8080,
      "redirects": null,
      "gzip_enabled": false,
      "cors_config": null,
      "aliases": null,
      "ssl_config": {
          "protocols": [
            "SSLv3",
            "SSLv2",
            "TLSv1",
            "TLSv1.1",
            "TLSv1.2"
          ],
        "require_client_certs": true,
        "trust_file": "/etc/proxy/tls/sidecar/ca.crt",
        "cert_key_pairs": [
          {
            "certificate_path": "/etc/proxy/tls/sidecar/server.crt",
            "key_path": "/etc/proxy/tls/sidecar/server.key"
          }
        ]
      },
      "force_https": true
    }
  listener.json: |-
    {
      "listener_key": "listener-gm-control-api",
      "zone_key": "zone-default-zone",
      "name": "gm-control-api",
      "ip": "0.0.0.0",
      "port": 8080,
      "protocol": "http_auto",
      "domain_keys": ["domain-gm-control-api"],
      "tracing_config": null
    }
  proxy.json: "{\n  \"proxy_key\": \"proxy-gm-control-api\",\n  \"zone_key\": \"zone-default-zone\",\n
    \ \"name\": \"gm-control-api\",\n  \"domain_keys\": [\n    \"domain-gm-control-api\"\n
    \ ],\n  \"listener_keys\": [\n      \"listener-gm-control-api\"\n  ],\n  \"listeners\":
    null,\n  \"active_proxy_filters\": [\n    \"gm.observables\",\n    \"gm.impersonation\",\n
    \   \"gm.metrics\"\n  ],\n  \"proxy_filters\": { \n    \"gm_observables\": {\n
    \     \"loglevel\": \"info\",\n      \"emitFullResponse\": \"false\",\n    },\n
    \   \"gm_impersonation\": {\n      \"servers\": \"C=US,ST=Virginia,L=Alexandria,O=Decipher
    Technology Studios,OU=Engineering,CN=edge|C=US,ST=Virginia,L=Alexandria,O=Decipher
    Technology Studios,OU=Engineering,CN=greymatter\"\n    },\n    \"gm_metrics\":
    {\n      \"metrics_port\": 8081,\n      \"metrics_host\": \"0.0.0.0\",\n      \"metrics_dashboard_uri_path\":
    \"/metrics\",\n      \"metrics_prometheus_uri_path\": \"/prometheus\",\n      \"prometheus_system_metrics_interval_seconds\":
    15,\n      \"metrics_ring_buffer_size\": 4096,\n      \"metrics_key_function\":
    \"depth\",\n      \"metrics_key_depth\": \"1\"\n    }\n  }\n}"
  route.json: |-
    {
      "route_key": "route-gm-control-api",
      "domain_key": "domain-gm-control-api",
      "zone_key": "zone-default-zone",
      "path": "/",
      "prefix_rewrite": null,
      "redirects": null,
      "shared_rules_key": "shared-rules-gm-control-api",
      "rules": null,
      "response_data": {},
      "cohort_seed": null,
      "retry_policy": null
    }
  shared_rules.json: |-
    {
      "shared_rules_key": "shared-rules-gm-control-api",
      "name": "gm-control-api",
      "zone_key": "zone-default-zone",
      "default": {
        "light": [
          {
            "constraint_key": "",
            "cluster_key": "cluster-gm-control-api",
            "metadata": null,
            "properties": null,
            "response_data": {},
            "weight": 1
          }
        ],
        "dark": null,
        "tap": null
      },
      "rules": null,
      "response_data": {},
      "cohort_seed": null,
      "properties": null,
      "retry_policy": null
    }
```

**Comment by tilleryd** [comment]
@bmheadley This PR is quite stale. We've moved observables configuration to `fabric/control-api/json/services/listener.json`. If you are still working on this please move the config there.

**Comment by tilleryd** [comment]
Closing as we are not focusing on release-2.1 anymore. This work should be performed against release-2.2

**Pull request closed without merging**
