### PR TITLE
 adds upgrade commands to each GM component

### LINKED ISSUE #705: Add update commands to helm charts
Currently the helm charts do not have an update command. We have makefiles for customers that have update commands.

### PR DESCRIPTION
**Pull request by chrisbsmith**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

Currently, the helm charts have no way of performing an upgrade. This adds a `make` command to each of the core Grey Matter charts.

closes #705 

2. What **changes to custom.yaml** are required?

nothing

3. Have you documented any additional setup steps or configurations options?

Yes, a new Readme has been created

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

```comamnd
make k3d
make secrets
make install
cd fabric
make upgrade-fabric
```

### CODE REVIEW

**Comment by chrisbsmith** [comment]
I found an issue with the secret upgrade, so I'm putting this in `WIP` until I resolve that

**Comment by chrisbsmith** [comment]
I've updated the steps to test and verify.  Below is my local validation:

# Install
```➜  secrets git:(make-upgrades) ✗ make secrets
cp ../credentials.yaml .
# Ensure that the rds.enabled is true in secrets and in fabric values files
rds.enabled in secrets/values.yaml and sense/values.yaml match
helm install secrets . -f credentials.yaml -f ../global.yaml
NAME: secrets
LAST DEPLOYED: Wed Jul 29 09:37:37 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
rm credentials.yaml
```

# Get Secrets

```
➜  secrets git:(make-upgrades) ✗ kc get secrets internal-data-secrets -o yaml
apiVersion: v1
data:
  aws_access_key_id: ""
  aws_region: ""
  aws_s3_bucket: bG9jYWw=
  aws_secret_access_key: ""
  master_key: blRpSGJrS1pLc3lYVGV0RHRXTVhhanZDdW9wZ1RteFQ=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: internal-data-secrets
  namespace: default
  resourceVersion: "80824"
  selfLink: /api/v1/namespaces/default/secrets/internal-data-secrets
  uid: a9f95895-c33a-4287-94e2-20c284dbb5e9
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets data-secrets -o yaml
apiVersion: v1
data:
  aws_access_key_id: QUtJQUlMU1hSVUFLNDRPTkkzTlE=
  aws_region: dXMtZWFzdC0x
  aws_s3_bucket: ZGVjaXBoZXItcXVpY2tzdGFydC1oZWxt
  aws_secret_access_key: V3NPNWhJVHdjMTFhVWhZdnhSQU1kQW1JN2VHeVhBSTQvcnFUN25NUQ==
  master_key: RE1oV3lRbFhwWlBseVlsUkdQRXJGTmNIQWRTdVFDQWk=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: data-secrets
  namespace: default
  resourceVersion: "80812"
  selfLink: /api/v1/namespaces/default/secrets/data-secrets
  uid: f098b9db-46ee-4091-9fab-a4f8daa0f247
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets -o yaml redis-password
apiVersion: v1
data:
  password: dFVmQXlqR1NLa0l0bmhRek9IeXVVQ3RPTEN4cVBta3k=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: redis-password
  namespace: default
  resourceVersion: "80814"
  selfLink: /api/v1/namespaces/default/secrets/redis-password
  uid: 4e10a469-48f3-4632-93f4-a0457a9cf005
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets -o yaml internal-redis-password
apiVersion: v1
data:
  password: WGN2V3dCalNacEVVWVBjcHdpWFB1SldDdkFkV09zemc=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: internal-redis-password
  namespace: default
  resourceVersion: "80817"
  selfLink: /api/v1/namespaces/default/secrets/internal-redis-password
  uid: 72f07136-1226-4022-b390-ac19d93a6bfb
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets -o yaml postgres-credentials
apiVersion: v1
data:
  database: Z3JleW1hdHRlcg==
  password: VEZVZVpCR1VGT3FyRmtkemtaRGhkSWZUelJTV1lrdU4=
  username: Z3JleW1hdHRlcg==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: postgres-credentials
  namespace: default
  resourceVersion: "80815"
  selfLink: /api/v1/namespaces/default/secrets/postgres-credentials
  uid: 1bbb0474-9fa1-488e-baeb-8c9d723f0307
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets mongo-password -o yaml
apiVersion: v1
data:
  database: Z21kYXRh
  gmdata_password: VEhRc01MQmN1VFJvcGVoYVhqa2dRZnl3VXhvVndEa0Y=
  gmdata_username: Z21kYXRhLXVzZXI=
  root_password: RGNjT3pka1ZDY3RNY2FqWUdpTnBkWE5wcnlNaHdnTFc=
  root_username: bW9uZ28=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:49:48Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: mongo-password
  namespace: default
  resourceVersion: "81698"
  selfLink: /api/v1/namespaces/default/secrets/mongo-password
  uid: 600c8504-bd3f-4bd7-a5ca-4030f7e54743
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets internal-mongo-password -o yaml
apiVersion: v1
data:
  database: Z21kYXRh
  gmdata_password: a052SkdaZEl1cExCTGlhSWRzUFRiWWlGTnpReENsSWI=
  gmdata_username: Z21kYXRhLXVzZXI=
  root_password: T2Zud2xMaFZSRndwVHp4SGFYcmVhTXlBUFZ3SlNiT0c=
  root_username: bW9uZ28=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:49:48Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: internal-mongo-password
  namespace: default
  resourceVersion: "81706"
  selfLink: /api/v1/namespaces/default/secrets/internal-mongo-password
  uid: fce0864f-6a1a-4eac-9726-f3f897774e73
type: Opaque
```

# Update Secrets
```
➜  secrets git:(make-upgrades) ✗ make upgrade-secrets
cp ../credentials.yaml .
# Ensure that the rds.enabled is true in secrets and in fabric values files
rds.enabled in secrets/values.yaml and sense/values.yaml match
helm upgrade secrets . -f credentials.yaml -f ../global.yaml --install
Release "secrets" has been upgraded. Happy Helming!
NAME: secrets
LAST DEPLOYED: Wed Jul 29 09:43:28 2020
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
rm credentials.yaml
```

## Validate that the Secrets are the same after upgrade
```
➜  secrets git:(make-upgrades) ✗ kc get secrets internal-data-secrets -o yaml
apiVersion: v1
data:
  aws_access_key_id: ""
  aws_region: ""
  aws_s3_bucket: bG9jYWw=
  aws_secret_access_key: ""
  master_key: blRpSGJrS1pLc3lYVGV0RHRXTVhhanZDdW9wZ1RteFQ=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: internal-data-secrets
  namespace: default
  resourceVersion: "80824"
  selfLink: /api/v1/namespaces/default/secrets/internal-data-secrets
  uid: a9f95895-c33a-4287-94e2-20c284dbb5e9
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets data-secrets -o yaml
apiVersion: v1
data:
  aws_access_key_id: QUtJQUlMU1hSVUFLNDRPTkkzTlE=
  aws_region: dXMtZWFzdC0x
  aws_s3_bucket: ZGVjaXBoZXItcXVpY2tzdGFydC1oZWxt
  aws_secret_access_key: V3NPNWhJVHdjMTFhVWhZdnhSQU1kQW1JN2VHeVhBSTQvcnFUN25NUQ==
  master_key: RE1oV3lRbFhwWlBseVlsUkdQRXJGTmNIQWRTdVFDQWk=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: data-secrets
  namespace: default
  resourceVersion: "80812"
  selfLink: /api/v1/namespaces/default/secrets/data-secrets
  uid: f098b9db-46ee-4091-9fab-a4f8daa0f247
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets -o yaml redis-password
apiVersion: v1
data:
  password: dFVmQXlqR1NLa0l0bmhRek9IeXVVQ3RPTEN4cVBta3k=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: redis-password
  namespace: default
  resourceVersion: "80814"
  selfLink: /api/v1/namespaces/default/secrets/redis-password
  uid: 4e10a469-48f3-4632-93f4-a0457a9cf005
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets -o yaml internal-redis-password
apiVersion: v1
data:
  password: WGN2V3dCalNacEVVWVBjcHdpWFB1SldDdkFkV09zemc=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: internal-redis-password
  namespace: default
  resourceVersion: "80817"
  selfLink: /api/v1/namespaces/default/secrets/internal-redis-password
  uid: 72f07136-1226-4022-b390-ac19d93a6bfb
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets -o yaml postgres-credentials
apiVersion: v1
data:
  database: Z3JleW1hdHRlcg==
  password: VEZVZVpCR1VGT3FyRmtkemtaRGhkSWZUelJTV1lrdU4=
  username: Z3JleW1hdHRlcg==
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:37:37Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: postgres-credentials
  namespace: default
  resourceVersion: "80815"
  selfLink: /api/v1/namespaces/default/secrets/postgres-credentials
  uid: 1bbb0474-9fa1-488e-baeb-8c9d723f0307
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets mongo-password -o yaml
apiVersion: v1
data:
  database: Z21kYXRh
  gmdata_password: VEhRc01MQmN1VFJvcGVoYVhqa2dRZnl3VXhvVndEa0Y=
  gmdata_username: Z21kYXRhLXVzZXI=
  root_password: RGNjT3pka1ZDY3RNY2FqWUdpTnBkWE5wcnlNaHdnTFc=
  root_username: bW9uZ28=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:49:48Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: mongo-password
  namespace: default
  resourceVersion: "81698"
  selfLink: /api/v1/namespaces/default/secrets/mongo-password
  uid: 600c8504-bd3f-4bd7-a5ca-4030f7e54743
type: Opaque
```
```
➜  secrets git:(make-upgrades) ✗ kc get secrets internal-mongo-password -o yaml
apiVersion: v1
data:
  database: Z21kYXRh
  gmdata_password: a052SkdaZEl1cExCTGlhSWRzUFRiWWlGTnpReENsSWI=
  gmdata_username: Z21kYXRhLXVzZXI=
  root_password: T2Zud2xMaFZSRndwVHp4SGFYcmVhTXlBUFZ3SlNiT0c=
  root_username: bW9uZ28=
kind: Secret
metadata:
  annotations:
    meta.helm.sh/release-name: secrets
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-07-29T13:49:48Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    chart: secrets-2.2.0
    heritage: Helm
    release: secrets
  name: internal-mongo-password
  namespace: default
  resourceVersion: "81706"
  selfLink: /api/v1/namespaces/default/secrets/internal-mongo-password
  uid: fce0864f-6a1a-4eac-9726-f3f897774e73
type: Opaque
```

# Verify All Services start with updates to the secrets yamls

```
cd secrets
make secrets
cd ..
make install
```

```
➜  helm-charts git:(make-upgrades) ✗ kc get pods
NAME                                     READY   STATUS      RESTARTS   AGE
internal-redis-665978b8fb-xn9hv          1/1     Running     0          2m32s
jwt-security-5c59f6cc46-n6wtj            2/2     Running     0          2m32s
redis-5c8d9dcf5d-972jj                   1/1     Running     0          2m32s
internal-jwt-security-69b5c68fd6-q2bnh   2/2     Running     0          2m32s
control-api-0                            2/2     Running     0          2m32s
control-api-init-82fbj                   0/1     Completed   0          2m31s
control-8494769c5f-m77x7                 1/1     Running     0          2m32s
edge-68c7cb869f-x8d5j                    1/1     Running     0          117s
internal-data-mongo-0                    1/1     Running     0          90s
data-internal-0                          2/2     Running     0          90s
prometheus-0                             2/2     Running     0          62s
postgres-slo-0                           1/1     Running     0          62s
slo-5d49c4c95-c8dvx                      2/2     Running     0          62s
catalog-678f489968-sbm28                 2/2     Running     0          62s
dashboard-84765d49d4-8pmz9               2/2     Running     0          62s
catalog-init-zm7c4                       0/1     Completed   0          36s
```

**Comment by chrisbsmith** [comment]
@sofiashalotenko please retest off commit `827713c7414ae86120d52d7e0e72c44665c2948e`

**Comment by tilleryd** [comment]
@sofiashalotenko this should resolve the dashboard not coming up https://github.com/DecipherNow/helm-charts/pull/711.

**Comment by chrisbsmith** [comment]
Awesome, thanks for running through this @sofiashalotenko !

**Pull request merged**
