### PR TITLE
update gm-data chart to enable/disable the internal and external data…

### PR DESCRIPTION
**Pull request by moosecanswim**
…s.  Match the values files to the parent values files for data

**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

Issue #640 .  Add the ability to deploy or not deploy data or internal data via values files

2. What **changes to custom.yaml** are required?

I updated the data/values.yaml file to more accuratly reflect all the values that can be changed in the sub-charts.  Also added `data.enabled` and `internal-data.enabled` keys to the parent chart values file.  

3. Have you documented any additional setup steps or configurations options?

none needed

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

`make delete` and `make install`  use `kubectl get pods`  to see data is present then `make delete` for a clean slate.
change the enable values i specified above to disable data.  
`make install` and `kubectl get pods` to make sure the instance of data you disabled does not show up

### CODE REVIEW

**Comment by chrisbsmith** [comment]
@moosecanswim can you explain why there are so many values that have now been commented out? I understand the addition of the conditional in the requirements.yaml and the related values in the chart, but why comment out so much other stuff?

**Comment by moosecanswim** [comment]
@chrisbsmith I updated the data/values.yaml so it accurately represents what can be changed.  When i went to deploy this in a production environment i had to constantly go back to the helm-charts source to see how to change values.  Many were missing.

**Comment by whenhellfreezes** [comment]
So it successfully doesn't deploy external data. However it will still make external data's gm configs so catalog is expecting a gm-data that isn't there. @moosecanswim

**Comment by chrisbsmith** [comment]
> So it successfully doesn't deploy external data. However it will still make external data's gm configs so catalog is expecting a gm-data that isn't there. @moosecanswim

The Catalog service is still looking for GM Data, so it will appear red in the dashboard

**Comment by moosecanswim** [comment]
you will need to remove the following from `sense/values.yaml` and `sense/catalog/values.yaml`: 
```
data:
    catalogEnabled: true
    controlEnabled: true
    name: 'Grey Matter Data'
    serviceName: 'data'
    observablesEnabled: false
    port: 8181
    enableInstanceMetrics: 'true'
    capability: 'Data'
    documentation: '/services/data/latest/static/ui/index.html'
    owner: 'Decipher'
    version: 1.1.0
    routes:
      - '/services/data/{{ $.Values.services.data.version }}'
      - '/services/data/{{ $.Values.services.data.version }}/'
    secret:
      enabled: true  
      secret_name: sidecar-certs
      mount_point: /etc/proxy/tls/sidecar
      insecure: true
      secret_keys:
        cert: server.crt
        key: server.key
        ca: ca.crt
```

**Pull request merged**
