### PR TITLE
updated gm-jwt-security-gov to version 1.1.2

### PR DESCRIPTION
**Pull request by dgoldstein1**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

- incorporate changes from https://github.com/DecipherNow/gm-jwt-security-gov/pull/138 and https://github.com/DecipherNow/gm-jwt-security-gov/pull/137

2. What **changes to custom.yaml** are required?

none

3. Have you documented any additional setup steps or configurations options?

n/a

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### CODE REVIEW

**Comment by moosecanswim** [comment]
@justincely I'm going to finish testing a standalone data chart, then test a couple more helm chart prs on my docket then hit this.  

My plan is to set up a new project in openshift and use this in place.

@dgoldstein1 could you test this against your eks deployment too?

**Comment by dgoldstein1** [comment]
@justincely 

The gm-jwt-gov repo is pushing to docker-dev.production.deciphernow.com but not docker.production.deciphernow.com

```bash
$ docker pull docker.production.deciphernow.com/deciphernow/gm-jwt-security-gov:1.1.2
Error response from daemon: manifest for docker.production.deciphernow.com/deciphernow/gm-jwt-security-gov:1.1.2 not found: manifest unknown: manifest unknown
```

How should we resolve this?

**Comment by justincely** [comment]
Right now there isn't a CI process to move things from -dev to prod.  I can move them myself

**Comment by justincely** [comment]
done, LMK if there are any issues

**Comment by dgoldstein1** [comment]
@moosecanswim tested this locally-- works OK. You will need to update the fabric values file when you want to deploy the gov jwt setup

**Comment by chrisbsmith** [comment]
@dgoldstein1 does JWT 1.1.2 bring just the new logging formats?

**Comment by dgoldstein1** [comment]
@chrisbsmith  yes

**Pull request merged**
