### PR TITLE
Updating appVersion to 2.2.0

### LINKED ISSUE #542: [release-2.2] - Update the Chart appVersion number for all NOTES.tpl files
With the installation of the release-2.2 branch of the Helm Charts, the versions represented in the charts.yaml file are not accurate, and so the print out to customers is incorrect.

Review all chart.yaml file and ensure the `{{ Chart.AppVersion}}` is correct

https://github.com/DecipherNow/helm-charts/blob/1074936fbce23860e960b056cec74651ff2862e7/edge/templates/NOTES.txt#L1

### PR DESCRIPTION
**Pull request by hiromis**
Closes #542 

Updated the `appVersion` to be 2.2.0, `apiVersion` to be v2 all across the board, and left `version` values as-is.

### CODE REVIEW

**Comment by chrisbsmith** [comment]
To be more specific, the `major.minor` of the `version` should match the release branch `major.minor`

**Comment by chrisbsmith** [comment]
@moosecanswim before you get too far, please review this PR.  I should've looked here first.

**Comment by tilleryd** [comment]
@hiromis This PR is stale. What do you plan to do with it?

**Comment by hiromis** [comment]
I am not sure. It depends on the disposition of https://github.com/DecipherNow/helm-charts/issues/542. It was waiting on @chrisbsmith's review the last time I touched.

**Comment by chrisbsmith** [comment]
It looks like @zoemccormick captured these changes in #664.  Recommend closing this PR.

**Comment by chrisbsmith** [comment]
@hiromis I think we can close this PR as OBE at this point.  If you agree, please close the PR.

**Comment by hiromis** [comment]
Sure, go ahead :)

**Pull request closed without merging**
