### PR TITLE
WIP: Data secret change

### PR DESCRIPTION
**Pull request by moosecanswim**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This updates data to allow user to
-  ignore deploying a docker image pull secret & specify image pull secret to use
- specify name from values.yaml (to support multiple gmdata in a namespace)
- updates sidecar envars to include ingress and proxy_dynamic envars

2. What **changes to custom.yaml** are required?

These were added
`createDockerSecret: true`
`data.replicas : 1`

### CODE REVIEW

**Comment by chrisbsmith** [comment]
@moosecanswim Your last comment on this PR was that you were working on a revamp.  If that's the case, can we close this PR to the work you're doing now?

**Comment by chrisbsmith** [comment]
@moosecanswim I know we talked about this after my comment, but I can't remember what we said.  This has been open for a bit now and I'm guessing there's been a lot of changes since it was submitted.  I'm going to close it as `stale` unless I hear from you by the end of the day.

**Comment by moosecanswim** [comment]
Yeah we should close this as stale but not delete the branch since the logic for future reworking of data might use this.

**Comment by moosecanswim** [comment]
We should set asside some time to do a rework because this chart has become super complicated since we keep bolting on more and more stuff @chrisbsmith

**Comment by chrisbsmith** [comment]
@moosecanswim i agree and i think we're going to make some make updates to the charts in the near future to try and simplify things.

**Pull request closed without merging**
