### PR TITLE
Sts data and control api

### PR DESCRIPTION
**Pull request by whenhellfreezes**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

Changing data and control api to be statefulsets instead of deployments so that you can do live updates easier. (For data when s3=false)

<br/><br/>

2. What **changes to custom.yaml** are required?

None.

<br/><br/>

3. Have you documented any additional setup steps or configurations options?

NA

<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Ran it in minikube successfully.

<br/><br/>

### CODE REVIEW

**Comment by chrisbsmith** [comment]
@whenhellfreezes do you have any idea how an "upgrade" for this PR would work?  Say I already have GM installed with a prior chart, what happens to the deployments for data and gm-control-api?

**Comment by moosecanswim** [comment]
> @whenhellfreezes do you have any idea how an "upgrade" for this PR would work? Say I already have GM installed with a prior chart, what happens to the deployments for data and gm-control-api?

The pvc will remain after the delete.  We may need to change the chart up for this case though.  aka, if there is a pvc that we want to use specify the name, otherwise create a new one.
(https://stackoverflow.com/questions/53186601/re-use-persistentvolume-after-re-installing-a-helm-deployment)

**Comment by whenhellfreezes** [comment]
I will test a helm upgrade with and without chart version increments to see exactly how this behaves.

**Comment by whenhellfreezes** [comment]
It will require a helm del and helm install to transition.

**Comment by whenhellfreezes** [comment]
Merged in master to make sure everything checks out and upped the version numbers. Note that I set gm-control-api from 2.2.1 to 2.1.3. The 2.2.1 was likely a typo.

**Pull request merged**
