### PR TITLE
Update helm chart references to new Nexus repo

### PR DESCRIPTION
**Pull request by dontlaugh**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

  We have a new Nexus server, but docs mention the old one

2. What **changes to custom.yaml** are required?

  N/A

3. Have you documented any additional setup steps or configurations options?

  N/A

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

  N/A

### CODE REVIEW

**Comment by chrisbsmith** [comment]
@dontlaugh I'm hesitant to approve this PR because this is 1 of many places where we need to update the configs.  Rather than piecemealing a bunch of PRs together, I'd like to see one that captures as many updates as possible.

Places to look / things to update:
- instructions for setting up the credentials to docker
- change all image locations from docker.production.deciphernow.com
- any other references

**Comment by dontlaugh** [comment]
Sure thing, here's a `ripgrep` of this repo
```
rg -F 'nexus.production.deciphernow.com' 
ci/Jenkinsfile
83:                        ./helm/helm repo add decipher https://nexus.production.deciphernow.com/repository/helm-hosted/ --username ${USERNAME} --password ${PASSWORD}
120:                                curl -u ${USERNAME}:${PASSWORD} https://nexus.production.deciphernow.com/repository/helm-hosted/ -T $pubChart
158:                                curl -u ${USERNAME}:${PASSWORD} https://nexus.production.deciphernow.com/repository/helm-hosted/ -T $pubChart
180:                                    curl -u ${USERNAME}:${PASSWORD} https://nexus.production.deciphernow.com/repository/helm-staging/ -T $pubChart
198:                        ./helm/helm repo add decipher-staging https://nexus.production.deciphernow.com/repository/helm-staging/ --username ${USERNAME} --password ${PASSWORD}
225:                                    curl -u ${USERNAME}:${PASSWORD} https://nexus.production.deciphernow.com/repository/helm-staging/ -T $pubChart

docs/Deploy with Minikube.md
290:helm repo add decipher https://nexus.production.deciphernow.com/repository/helm-hosted --username <username> --password '<password>'

docs/Generic Install.md
50:Once you have the desired configurations, and account credentials to access to [Deciphers Nexus Repository](https://nexus.production.deciphernow.com/#browse/welcome), you can install using the hosted helm charts:
53:helm repo add decipher https://nexus.production.deciphernow.com/repository/helm-hosted --username 'YOUR USERNAME' --password 'YOUR PASSWORD'

ci/scripts/build-credentials.sh
27:helm repo add decipher https://nexus.production.deciphernow.com/repository/helm-hosted --username $EMAIL --password $PASSWORD
```
There are a couple of other markdown places. I'm inclined to leave the Jenkinsfile to you, however.

**Comment by dontlaugh** [comment]
I added a few changes. If you think it's safe to just update the Jenkins file, I can do that. I don't know how to test, though.

**Comment by chrisbsmith** [comment]
@dontlaugh can you run the same grep for `docker.production.deciphernow.com`?  That's gonna pop a lot more because of all the images.

I'd expect to see a bunch of files and lines like this:

https://github.com/DecipherNow/helm-charts/blob/95e38c5e54a064a4da0b3b527d4d3eaa07708555/data/values.yaml#L88

**Comment by chrisbsmith** [comment]
Though I suppose if you're only updating the documentation this will suffice.  The charts as pushed to nexus.greymatter.io should reference images at docker.production.deciphernow.com.

OK, Let me review.  This may be fine. The chart DO need to be updated to find images are the correct location, but we can do that in a later step.

**Comment by dontlaugh** [comment]
<details>
<summary>`rg -F 'docker.production.deciphernow.com/deciphernow/'`</summary>

```
data/configuration.md
71:|data.data.image                                    |docker.production.deciphernow.com/deciphernow/gm-data:{{ .Values.data.version }}|

data/values.yaml
88:    image: 'docker.production.deciphernow.com/deciphernow/gm-data:{{ .Values.data.version }}'
298:    image: 'docker.production.deciphernow.com/deciphernow/gm-data:{{ .Values.data.version }}'

sense/values.yaml
67:    image: 'docker.production.deciphernow.com/deciphernow/gm-slo:{{ $.Values.slo.version }}'
209:    image: 'docker.production.deciphernow.com/deciphernow/gm-dashboard:{{ $.Values.dashboard.version }}'
319:    image: docker.production.deciphernow.com/deciphernow/gm-catalog:{{ $.Values.catalog.version }}

sense/configuration.md
34:|slo.slo.image                                  |           |docker.production.deciphernow.com/deciphernow/gm-slo:{{ $.Values.slo.version }}                                   |
121:|dashboard.dashboard.image                             |           |docker.production.deciphernow.com/deciphernow/gm-dashboard:{{ $.Values.dashboard.version }}|

fabric/configuration.md
40:|jwt.jwt.image                        |           |docker.production.deciphernow.com/deciphernow/gm-jwt-security:{{ .Values.jwt.version }}|
77:|control.control.image                                               |           |docker.production.deciphernow.com/deciphernow/gm-control:{{ $.Values.control.version }}               |
125:|control-api.controlApi.image                                        |           |docker.production.deciphernow.com/deciphernow/gm-control-api:{{ $.Values.controlApi.version }}        |

fabric/values.yaml
80:    image: 'docker.production.deciphernow.com/deciphernow/gm-control:{{ $.Values.control.version }}'
172:    image: 'docker.production.deciphernow.com/deciphernow/gm-control-api:{{ $.Values.controlApi.version }}'
500:    image: 'docker.production.deciphernow.com/deciphernow/gm-jwt-security:{{ .Values.jwt.version }}'
559:    image: 'docker.production.deciphernow.com/deciphernow/gm-jwt-security:{{ .Values.jwt.version }}'

edge/values.yaml
38:  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.edge.version $ }}'

edge/configuration.md
31:|edge.image                                                                   |           |docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.edge.version $ }}|

data/gm-data/values.yaml
47:  image: docker.production.deciphernow.com/deciphernow/gm-data:{{ $.Values.data.version }}
282:  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'

data/gm-data/configuration.md
35:|data.image                             |           |docker.production.deciphernow.com/deciphernow/gm-data:{{ $.Values.data.version }}                      |
152:|sidecar.image                    |           |docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}|

sense/slo/values.yaml
39:  image: "docker.production.deciphernow.com/deciphernow/gm-slo:{{ .Values.slo.version }}"
116:  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'

sense/slo/configuration.md
29:|sidecar.image                    |           |docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}|

sense/dashboard/values.yaml
37:  image: 'docker.production.deciphernow.com/deciphernow/gm-dashboard:{{ $.Values.dashboard.version }}'
97:  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar_dashboard.version $ }}'
165:  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar_prometheus.version $ }}'

sense/dashboard/configuration.md
28:|sidecar_dashboard.image                     |           |docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar_dashboard.version $ }} |
45:|sidecar_prometheus.image                    |           |docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar_prometheus.version $ }}|

sense/catalog/values.yaml
47:  image: docker.production.deciphernow.com/deciphernow/gm-catalog:{{ $.Values.catalog.version }}
146:    image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
174:  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'

sense/catalog/configuration.md
29:|sidecar.image                    |           |docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}|

fabric/control/values.yaml
39:  image: 'docker.production.deciphernow.com/deciphernow/gm-control:{{ $.Values.control.version }}'

fabric/jwt/values.yaml
35:  image: 'docker.production.deciphernow.com/deciphernow/gm-jwt-security:{{ tpl $.Values.jwt.version $ }}'
226:  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'

fabric/control-api/values.yaml
56:  image: 'docker.production.deciphernow.com/deciphernow/gm-control-api:{{ .Values.controlApi.version }}'
112:  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
138:  image: 'docker.production.deciphernow.com/deciphernow/greymatter:1.4.2'

fabric/control-api/configuration.md
36:|sidecar.image                    |           |docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}|

fabric/jwt/configuration.md
26:|jwt.image                      |           |docker.production.deciphernow.com/deciphernow/gm-jwt-security:{{ tpl $.Values.jwt.version $ }}                                        |
81:|sidecar.image                    |           |docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}|

fabric/jwt-gov/configuration.md
23:|sidecar.image                |           |docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}|

fabric/jwt-gov/values.yaml
222:  image: 'docker.production.deciphernow.com/deciphernow/gm-proxy:{{ tpl $.Values.sidecar.version $ }}'
```

</details>

**Comment by dontlaugh** [comment]
Here are some regexes I did for the CI in gm-control-api for this. There were a few stragglers at the end of it.
https://github.com/DecipherNow/gm-control-api/issues/509

**Comment by dontlaugh** [comment]
Thanks! I don't have perms to merge so can you take care of it?

**Pull request merged**
