### PR TITLE
Add default consul values to the slo chart

### LINKED ISSUE #321: slo missing global.consul.enabled check
The SLO chart is missing the `.Values.global.consul.enabled` in slo/values.yaml.  This is causing templating errors

### PR DESCRIPTION
**Pull request by chrisbsmith**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

Resolves #321 

The SLO chart did not have a default setting for consul, so if someone tried to install Grey Matter with an old yaml file, it would fail.

2. What **changes to custom.yaml** are required?

n/a

3. Have you documented any additional setup steps or configurations options?

n/a
4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### CODE REVIEW

**Comment by tilleryd** [comment]
@chrisbsmith Is it our strategy to always add global variables to each chart? I can see us bloating all of the charts in this manner. Wouldn't a better strategy to always point users to the latest ./greymatter.yaml file?

**Comment by chrisbsmith** [comment]
@tilleryd global variables only need to be added to the chart that requires them.  For instance, in this example, the new global variable `.Values.global.consul.enabled` was added to slo.  When Parth attempted to deploy the Grey Matter chart without the updates to `greymatter.yaml`, SLO failed.  Each chart should be able to be deployed individually (even though the Grey Matter Helm chart), so each chart's value.yaml file should contain all variables it needs to run.

If other charts don't need `.Values.global.consul.enabled` then there's no need to create that option to the chart's values.yaml file.

**Comment by tilleryd** [comment]
@chrisbsmith Got it. @zoemccormick I suggest just adding to the PR for the other charts.

**Comment by tilleryd** [comment]
@chrisbsmith I just successfully installed without providing any global Consul configs in `./custom-greymatter.yaml`. Once the conflicts are resolved and chart versions are updated I'll approve.

**Pull request merged**
