### PR TITLE
Removing if statements

### PR DESCRIPTION
**Pull request by hiromis**
After upgrading helm to v3.3.4, I started to get the following error:

```
Error: template: fabric/charts/jwt/templates/jwt.yaml:51:12: executing "fabric/charts/jwt/templates/jwt.yaml" at <include "sidecar.envvars" .>: error calling include: template: fabric/charts/control-api/templates/_envvars.tpl:53:10: executing "sidecar.envvars" at <include "envvar" $args>: error calling include: template: fabric/charts/control-api/templates/_envvars.tpl:36:19: executing "envvar" at <(tpl $e.value $top) ne "">: can't give argument to non-function tpl $e.value $top
make[1]: *** [fabric] Error 1
make: *** [install] Error 2
```

Due to the comment above the if statement suggested of removal 7 months ago, rather than fixing the if statement, removing them all together.

Here is the version of my helm:

```bash
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"dirty", GoVersion:"go1.15.2"}
```

How I tested the PR:
Followed `Deploy with K3d.md`
1. `make k3d` - start a kubernetes cluster locally.
2. `export KUBECONFIG=$(k3d kubeconfig write greymatter)` - configures `kubectl` to use the local k3d cluster.
3. `make credentials` - creates a git ignored file `credentials.yaml`
4. `make secrets` - inserts data from `credentials.yaml` and `secrets/values.yaml` into the cluster as secrets
5. `make install` - installs each helm chart (spire, fabric, edge, data, sense). Make sure that the error is gone.

### CODE REVIEW

**Comment by chrisbsmith** [comment]
@hiromis , I am getting this error from edge when trying to install. I'm looking at the mesh configs and nothing seems out of the ordinary. Have you seen this before?

```
[2020-10-16 13:19:35.289][17][warning][config] [external/envoy/source/server/listener_impl.cc:196] Listener connection limit runtime key envoy.resource_limits.listener.edge:10808.connection_limit is empty. There are currently no limitations on the number of accepted connections for listener edge:10808.
[2020-10-16 13:19:35.309][17][warning][config] [external/envoy/source/server/listener_impl.cc:196] Listener connection limit runtime key envoy.resource_limits.listener.edge:10909.connection_limit is empty. There are currently no limitations on the number of accepted connections for listener edge:10909.
[2020-10-16 13:19:35.310][17][warning][config] [external/envoy/source/common/config/grpc_subscription_impl.cc:87] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener(s) edge:10808: Didn't find a registered implementation for name: 'envoy.filters.network.http_connection_manager'
edge:10909: Didn't find a registered implementation for name: 'envoy.filters.network.http_connection_manager'
```

I have not seen this before

**Comment by hiromis** [comment]
I believe I saw it before this PR got merged https://github.com/DecipherNow/helm-charts/pull/758 but have not seen it since.

**Comment by hiromis** [comment]
I merged up the change to this branch.

**Comment by chrisbsmith** [comment]
Thanks @hiromis. That did it.  I rebased your branch on release-2.3 and the system came up as expected!

**Review by chrisbsmith — APPROVED** [review]
LGTM, tested locally

**Pull request merged**
