### PR TITLE
Allow script to setup S3 as well.

### PR DESCRIPTION
**Pull request by whenhellfreezes**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This change will allow the quickstart credentials builder to config S3 properly. This is the follow on PR based on tilleryd's suggestions.

<br/><br/>

2. What **changes to custom.yaml** are required?

None

<br/><br/>

3. Have you documented any additional setup steps or configurations options?

Yes

<br/><br/>

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Exercise for the user.
<br/><br/>

### CODE REVIEW

**Comment by tilleryd** [comment]
@whenhellfreezes PR https://github.com/DecipherNow/helm-charts/pull/341/files removed `./greymatter-minikube`. You will need to update your scripts accordingly to handle the new convention as [documented here](https://github.com/DecipherNow/helm-charts/blob/release-2.0/docs/Deploy%20with%20Minikube.md#latest-helm-charts-release).

**Comment by tilleryd** [comment]
@whenhellfreezes Can you also add this step to the process?

```
minikube -p gm-deploy service --https=true voyager-edge
```

This will expose the edge to the outside world and automatically open up browser tabs to the dashboard.

**Comment by whenhellfreezes** [comment]
Fixed the greymatter-minikube.yaml and adding minikube service list. Pushing as new commit.

**Comment by whenhellfreezes** [comment]
Going to show url instead of opening a tab.

**Comment by tilleryd** [comment]
@whenhellfreezes Running `minikube -p gm-deploy service --https=true voyager-edge` aligns with the manual steps. If you run that, Voyager will automatically open browser tabs. Why do you prefer otherwise?

**Comment by whenhellfreezes** [comment]
Well I don't like commands opening a tab. It also causes trouble when executing on a remote machine.

**Comment by tilleryd** [comment]
@whenhellfreezes Ok, your suggestion makes sense for machines that don't have browsers. I updated the `awk` command with the nice string for end users.

**Pull request merged**
