### PR TITLE
gm-dashboard 3.4.0

### PR DESCRIPTION
**Pull request by tilleryd**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

n/a

2. What **changes to custom.yaml** are required?

n/a

3. Have you documented any additional setup steps or configurations options?

n/a

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

n/a

### CODE REVIEW

**Comment by tilleryd** [comment]
@justincely FYI

**Comment by tilleryd** [comment]
@kaitmore or @chrisbsmith what do I need to update to fix the failing `package-and-publish-greymatter-staging` check?

**Comment by chrisbsmith** [comment]
Well for starters it doesn't look like you updated the version in the `Chart.yaml` files, and subsequent `requirements.yaml`.  

If that doesn't resolve it then @moosecanswim will need to resolve

**Comment by tilleryd** [comment]
@chrisbsmith Thanks I missed that one.

**Comment by tilleryd** [comment]
@kaitmore or @chrisbsmith or @moosecanswim can I have this PR approved tonight please? It's high priority. Thanks.

**Pull request merged**
