### PR TITLE
Adds the missing spaces in the global zone templating

### LINKED ISSUE #514: Current Helm Charts do not template the Mesh configuration properly
At some point in the recent history, the Grey Matter Mesh configuration was modified to allow users to template the default zone.  However, many of the configurations do not template properly.  This is an example of the current logs from GM Control API

```json
{"level":"error","service":"gm-control-api","handler":"/v1.0/zone/{{+.Values.global.zone+}}","method":"GET","headers":"(User-Agent, Go-http-client/1.1), (Authorization, xxx), (X-Gm-Api-Client-App, github.com/deciphernow/gm-control), (X-Gm-Api-Client-Type, github.com/deciphernow/gm-control-api/api/client), (X-Gm-Api-Client-Version, v1.1.0), (Accept-Encoding, gzip)","Zone().Get":"Not found","Key":"{{+.Values.global.zone+}}","method":"GET","code":400,"time":"2020-03-17T19:29:08Z","message":"Index"}
```

You can see that the `{{ .Values.global.zone }}` field did not template.  This is because in the YAML files, there is not a space ` ` between the `{{` and the `.` and the `e` and `}}`.  This prevents the Helm from templating the fields.

This is a major break and prevents the Helm charts from deploying Grey Matter.

### PR DESCRIPTION
**Pull request by chrisbsmith**
**Please provide enough information so that others can review your pull request:**

1. Explain the **details** for making this change. What existing problem does the pull request solve? If it resolves an existing issue, be sure to use a Github [keyword](https://help.github.com/en/articles/closing-issues-using-keywords) to automatically close it.

This PR fixes #514 and allows Helm to once again properly template the global zones for all of the mesh configurations.

2. What **changes to custom.yaml** are required?

none

3. Have you documented any additional setup steps or configurations options?

none

4. Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

I caught the error attempting to deploy in [k3d](https://github.com/rancher/k3d).

The original error:

```json
{"level":"error","service":"gm-control-api","handler":"/v1.0/zone/{{+.Values.global.zone+}}","method":"GET","headers":"(Accept-Encoding, gzip), (User-Agent, Go-http-client/1.1), (Authorization, xxx), (X-Gm-Api-Client-App, github.com/deciphernow/gm-control), (X-Gm-Api-Client-Type, github.com/deciphernow/gm-control-api/api/client), (X-Gm-Api-Client-Version, v1.1.0)","Zone().Get":"Not found","Key":"{{+.Values.global.zone+}}","method":"GET","code":400,"time":"2020-03-17T19:16:05Z","message":"Index"}
```

After updating the charts locally and redeploying

```json
{"level":"debug","service":"gm-control-api","handler":"/v1.0/cluster/edge-to-slo-cluster","method":"PUT","headers":"(X-Gm-Api-Client-Type, github.com/deciphernow/gm-control-api/api/client), (X-Gm-Api-Client-Version, v1.1.0), (Accept-Encoding, gzip), (User-Agent, Go-http-client/1.1), (Content-Length, 704), (Authorization, xxx), (X-Gm-Api-Client-App, github.com/deciphernow/gm-control)","cluster":"{ClusterKey:edge-to-slo-cluster ZoneKey:zone-default-zone Name:slo RequireTLS:true Secret:{SecretKey: Name: ValidationName: Subjects:[] ECDHCurves:[] ForwardClientCertDetails: SetCurrentClientCertDetails:{URI:false} Checksum:{Checksum:}} SSLConfig:0xc000062d80 Instances:[] OrgKey: CircuitBreakersThresholds:<nil> OutlierDetection:<nil> HealthChecks:[] Checksum:{Checksum:335c4e3e0465d0a0c7f6747b5ecb7f875ddd9f52d0f89ab173bc9a6624fda5ad}}","time":"2020-03-17T19:36:09Z","message":"handleV1ClusterPUT"}
```

image

### CODE REVIEW

**Comment by whenhellfreezes** [comment]
With greymater/Chart.yaml updated this looks good to me.

**Comment by whenhellfreezes** [comment]
May want to bump gmControlApi chart number too.

**Comment by chrisbsmith** [comment]
thanks @whenhellfreezes .  Good catch

**Comment by moosecanswim** [comment]
Works as expected!

**Pull request merged**
